#!/usr/bin/env python3
"""
Generate Claude Code + Codex chat digests with guaranteed file saving.

Session discovery — priority order:
  1. JSONL scan: reads ~/.claude/projects/*/*.jsonl directly (always current)
  2. Day-tracker daily JSONs: ~/Documents/day-tracker/data/daily/YYYY-MM-DD.json
     — canonical time-based confirmation of which sessions were active
     — fills projects not covered by JSONL scan
  3. sessions-index.json: legacy fallback, only when non-stale entries exist

Deterministic parts (script handles):
- Finding sessions across all projects (Claude Code + Codex)
- Loading last digest to get period.to timestamp
- Filtering sessions by timestamp
- Grouping by project
- Calculating session counts
- Extracting session summaries
- SAVING THE FILE (guaranteed - can't be forgotten)

Judgment parts (Claude can enhance after):
- Writing narrative combined_summary for each project
- Identifying key_completions, still_in_progress, all_blockers
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

from config import (
    CLAUDE_DIR,
    CODEX_SESSIONS_DIR,
    DAY_TRACKER_DAILY_DIR,
    DIGESTS_DIR,
    PROJECTS_DIR,
    PROJECTS_YAML,
)

# Fixed CET offset (UTC+1) used for naive day-tracker timestamps
# Acceptable approximation; off by 1h during CEST (late Mar–late Oct)
_CET = timezone(timedelta(hours=1))


# ---------------------------------------------------------------------------
# Timestamp helpers
# ---------------------------------------------------------------------------

def parse_timestamp(ts: str) -> datetime:
    """Parse an ISO timestamp string to timezone-aware datetime."""
    if ts.endswith("Z"):
        ts = ts[:-1] + "+00:00"
    dt = datetime.fromisoformat(ts)
    if dt.tzinfo is None:
        # Treat naive timestamps as CET (day-tracker local time)
        dt = dt.replace(tzinfo=_CET)
    return dt


def mtime_dt(path: Path) -> datetime:
    """Return file modification time as timezone-aware UTC datetime."""
    return datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)


# ---------------------------------------------------------------------------
# JSONL turn extraction (adapted from agent-conversations script)
# ---------------------------------------------------------------------------

_XML_TAG_RE = re.compile(r"<[^>]+>")
_WHITESPACE_RE = re.compile(r"\s+")
_IGNORE_PREFIXES = (
    "Caveat: The messages below were generated by the user while running local commands",
    "# AGENTS.md instructions",
    "<environment_context>",
)
_MAX_TURN_CHARS = 280
_MAX_USER_TURNS = 4
_MAX_ASSISTANT_TURNS = 3


def _normalize_text(text: str) -> str:
    """Clean up turn text: strip XML tags, collapse whitespace, truncate."""
    if not text or not isinstance(text, str):
        return ""
    cleaned = _XML_TAG_RE.sub("", text)
    cleaned = _WHITESPACE_RE.sub(" ", cleaned).strip()
    if not cleaned or any(cleaned.startswith(p) for p in _IGNORE_PREFIXES):
        return ""
    return cleaned[:_MAX_TURN_CHARS]


def _extract_user_text(entry: dict) -> str:
    """Extract user message text from a JSONL entry."""
    msg = entry.get("message")
    if isinstance(msg, str):
        return _normalize_text(msg)
    if not isinstance(msg, dict):
        return ""
    content = msg.get("content", "")
    if isinstance(content, str):
        return _normalize_text(content)
    if isinstance(content, list):
        for block in content:
            if not isinstance(block, dict) or block.get("type") != "text":
                continue
            text = _normalize_text(block.get("text", ""))
            if text:
                return text
    return ""


def _extract_assistant_text(entry: dict) -> str:
    """Extract assistant message text from a JSONL entry."""
    msg = entry.get("message")
    if not isinstance(msg, dict):
        return ""
    content = msg.get("content", [])
    if not isinstance(content, list):
        return ""
    parts = []
    for block in content:
        if not isinstance(block, dict) or block.get("type") != "text":
            continue
        cleaned = _normalize_text(block.get("text", ""))
        if cleaned:
            parts.append(cleaned)
    return " ".join(parts).strip()[:_MAX_TURN_CHARS]


def _append_turn(items: list, text: str, limit: int) -> None:
    """Append a turn to the list, deduplicating and capping length."""
    if not text or (items and items[-1] == text):
        return
    items.append(text)
    if len(items) > limit:
        del items[: len(items) - limit]


def extract_session_turns(jsonl_path: Path, max_bytes: int = 100_000) -> dict:
    """
    Read the tail of a JSONL session file and extract recent user/assistant turns.

    Returns {"recentUserTurns": [...], "recentAssistantTurns": [...]}.
    """
    user_turns: list[str] = []
    assistant_turns: list[str] = []

    try:
        file_size = os.path.getsize(jsonl_path)
        with open(jsonl_path, encoding="utf-8", errors="replace") as f:
            if file_size > max_bytes:
                f.seek(file_size - max_bytes)
                f.readline()  # skip partial first line
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue

                entry_type = entry.get("type")
                if entry_type == "user":
                    _append_turn(user_turns, _extract_user_text(entry), _MAX_USER_TURNS)
                elif entry_type == "assistant":
                    _append_turn(assistant_turns, _extract_assistant_text(entry), _MAX_ASSISTANT_TURNS)
    except OSError:
        pass

    return {
        "recentUserTurns": user_turns,
        "recentAssistantTurns": assistant_turns,
    }


# ---------------------------------------------------------------------------
# Source 3 (legacy): sessions-index.json
# ---------------------------------------------------------------------------

def index_is_stale(index_data: dict, since: Optional[str]) -> bool:
    """Return True if the index has no entries newer than `since`."""
    if not since:
        return False
    entries = index_data.get("entries", [])
    if not entries:
        return True
    since_dt = parse_timestamp(since)
    for e in entries:
        ts = e.get("modified") or e.get("created", "")
        if ts:
            try:
                if parse_timestamp(ts) > since_dt:
                    return False
            except ValueError:
                pass
    return True


def find_session_files() -> list[Path]:
    """Find all sessions-index.json files in ~/.claude/projects/."""
    return list(PROJECTS_DIR.glob("*/sessions-index.json"))


def load_sessions(paths: list[Path], since: Optional[str] = None) -> list[dict]:
    """Load non-stale session entries from sessions-index.json files."""
    all_sessions = []
    for path in paths:
        try:
            with open(path) as f:
                data = json.load(f)
            if since and index_is_stale(data, since):
                continue
            entries = data.get("entries", [])
            for entry in entries:
                entry["_source_file"] = str(path)
                entry["_source"] = "claude"
            all_sessions.extend(entries)
        except (json.JSONDecodeError, OSError) as e:
            print(f"Warning: Could not load {path}: {e}", file=sys.stderr)
    return all_sessions


# ---------------------------------------------------------------------------
# Source 1 (primary): direct JSONL scan
# ---------------------------------------------------------------------------

def extract_jsonl_metadata(jsonl_path: Path) -> Optional[dict]:
    """
    Extract session metadata from a JSONL file by reading up to 50 lines.

    Handles two formats:
    - Newer: starts with file-history-snapshot, then progress line with cwd/sessionId
    - Older: starts with queue-operation (sessionId, timestamp)
    """
    session_id = None
    project_path = None
    created = None
    first_prompt = None

    try:
        with open(jsonl_path, encoding="utf-8", errors="replace") as f:
            for i, raw_line in enumerate(f):
                if i >= 50:
                    break
                try:
                    obj = json.loads(raw_line)
                except json.JSONDecodeError:
                    continue

                obj_type = obj.get("type", "")

                # Pick up sessionId from queue-operation or any line that has it
                if session_id is None and obj.get("sessionId"):
                    session_id = obj["sessionId"]

                # Pick up cwd (projectPath) from progress/user/assistant lines
                if project_path is None and obj.get("cwd"):
                    project_path = obj["cwd"]

                # Pick up created timestamp
                if created is None:
                    if obj_type == "queue-operation" and obj.get("timestamp"):
                        created = obj["timestamp"]
                    elif obj.get("timestamp") and project_path:
                        # Use first timestamped line after we have context
                        created = obj["timestamp"]

                # Pick up first user prompt (skip system messages)
                if first_prompt is None and obj_type == "user":
                    msg = obj.get("message", {})
                    content = msg.get("content", [])
                    if isinstance(content, list):
                        for part in content:
                            if not isinstance(part, dict):
                                continue
                            text = part.get("text", "")
                            # Skip system instructions and very short texts
                            if text.startswith("#") or text.startswith("<") or len(text) < 10:
                                continue
                            first_prompt = text[:200]
                            break
                    elif isinstance(content, str) and len(content) >= 10:
                        if not content.startswith("#") and not content.startswith("<"):
                            first_prompt = content[:200]

                # Stop early once we have everything
                if session_id and project_path and created and first_prompt:
                    break

    except OSError as e:
        print(f"Warning: Could not read {jsonl_path}: {e}", file=sys.stderr)
        return None

    # Need at least a project path to be useful
    if not project_path:
        return None

    # Fallback: use file mtime as created if we couldn't find a timestamp
    if not created:
        created = mtime_dt(jsonl_path).isoformat()

    # Use file mtime as modified (always reliable)
    modified = mtime_dt(jsonl_path).isoformat()

    # Extract recent turns from the tail of the file
    turns = extract_session_turns(jsonl_path)

    return {
        "sessionId": session_id,
        "projectPath": project_path,
        "created": created,
        "modified": modified,
        "summary": "",
        "firstPrompt": first_prompt or "",
        "recentUserTurns": turns["recentUserTurns"],
        "recentAssistantTurns": turns["recentAssistantTurns"],
        "_source_file": str(jsonl_path),
        "_source": "claude-jsonl",
    }


def scan_jsonl_sessions(since: Optional[str]) -> list[dict]:
    """
    Scan ~/.claude/projects/*/*.jsonl directly for session metadata.

    For each project directory:
    - Skips if a non-stale sessions-index.json exists (legacy path handles it)
    - Otherwise reads *.jsonl files modified after `since`
    """
    if not PROJECTS_DIR.exists():
        return []

    since_dt = parse_timestamp(since) if since else None
    sessions = []
    seen_ids: set[str] = set()

    for project_dir in sorted(PROJECTS_DIR.iterdir()):
        if not project_dir.is_dir():
            continue

        # Skip if this project has a non-stale sessions-index.json
        index_path = project_dir / "sessions-index.json"
        if index_path.exists():
            try:
                index_data = json.loads(index_path.read_text())
                if not index_is_stale(index_data, since):
                    continue  # Non-stale index; legacy path handles this project
            except (json.JSONDecodeError, OSError):
                pass  # Corrupt index — fall through to JSONL scan

        # Scan JSONL files in this directory
        for jsonl_path in sorted(project_dir.glob("*.jsonl")):
            # mtime pre-filter: skip files not touched since the cutoff
            if since_dt and mtime_dt(jsonl_path) <= since_dt:
                continue

            session = extract_jsonl_metadata(jsonl_path)
            if not session:
                continue

            # Deduplicate by sessionId
            sid = session.get("sessionId")
            if sid:
                if sid in seen_ids:
                    continue
                seen_ids.add(sid)

            sessions.append(session)

    print(f"JSONL scan: {len(sessions)} sessions from direct file scan", file=sys.stderr)
    return sessions


# ---------------------------------------------------------------------------
# Source 2 (supplementary): day-tracker active_sessions
# ---------------------------------------------------------------------------

def load_sessions_from_day_tracker(since: Optional[str]) -> list[dict]:
    """
    Load Claude Code sessions from day-tracker daily JSON files.

    Day-tracker captures active Claude Code sessions every ~5 minutes.
    We deduplicate by (project_path, title) to get one entry per unique session per day.

    Only includes projects NOT already covered by JSONL scan or non-stale index
    (caller handles filtering via covered_projects set).
    """
    if not DAY_TRACKER_DAILY_DIR.exists():
        print("Day-tracker daily dir not found; skipping", file=sys.stderr)
        return []

    since_dt = parse_timestamp(since) if since else None
    # Key: (project_path, title) → session dict
    seen: dict[tuple, dict] = {}

    daily_files = sorted(DAY_TRACKER_DAILY_DIR.glob("*.json"))
    for daily_file in daily_files:
        try:
            date_str = daily_file.stem  # e.g. "2026-03-08"
            # Skip sync-conflict files and other non-date filenames
            if len(date_str) != 10:
                continue
            # Quick date-based pre-filter (file date < since date → skip)
            if since_dt:
                file_date = datetime.strptime(date_str, "%Y-%m-%d").replace(tzinfo=_CET)
                if file_date.date() < since_dt.date():
                    continue

            data = json.loads(daily_file.read_text())
            entries = data.get("entries", [])

            for entry in entries:
                entry_ts_str = entry.get("timestamp", "")
                if not entry_ts_str:
                    continue

                # Day-tracker timestamps are naive local; parse_timestamp adds CET offset
                try:
                    entry_ts = parse_timestamp(entry_ts_str)
                except ValueError:
                    continue

                if since_dt and entry_ts <= since_dt:
                    continue

                active_sessions = entry.get("active_sessions") or []
                for sess in active_sessions:
                    if sess.get("agent") != "claude":
                        continue

                    project_path = sess.get("project_path", "")
                    title = sess.get("title", "")
                    key = (project_path, title)

                    if key not in seen:
                        seen[key] = {
                            "sessionId": None,
                            "projectPath": project_path,
                            "created": entry_ts_str,
                            "modified": entry_ts_str,
                            "summary": title,
                            "firstPrompt": "",
                            "_source_file": str(daily_file),
                            "_source": "day-tracker",
                        }
                    else:
                        seen[key]["modified"] = entry_ts_str

        except (json.JSONDecodeError, OSError, ValueError) as e:
            print(f"Warning: Could not read day-tracker file {daily_file}: {e}", file=sys.stderr)

    sessions = list(seen.values())
    print(f"Day-tracker: {len(sessions)} unique sessions from daily logs", file=sys.stderr)
    return sessions


# ---------------------------------------------------------------------------
# Session merging
# ---------------------------------------------------------------------------

def merge_sessions(
    index_sessions: list[dict],
    jsonl_sessions: list[dict],
    dt_sessions: list[dict],
    since: Optional[str],
) -> list[dict]:
    """
    Merge sessions from all three sources with deduplication.

    Priority:
    1. JSONL sessions (have session IDs, most accurate)
    2. Index sessions (non-stale only — already filtered by load_sessions)
    3. Day-tracker sessions (only for projects not covered by JSONL or index)
    """
    merged: list[dict] = []
    seen_ids: set[str] = set()

    # Projects covered by JSONL or index (by projectPath)
    covered_paths: set[str] = set()

    # 1. Add JSONL sessions
    for s in jsonl_sessions:
        sid = s.get("sessionId")
        if sid:
            if sid in seen_ids:
                continue
            seen_ids.add(sid)
        merged.append(s)
        covered_paths.add(s.get("projectPath", ""))

    # 2. Add index sessions (non-stale, already filtered)
    for s in index_sessions:
        sid = s.get("sessionId")
        if sid:
            if sid in seen_ids:
                continue
            seen_ids.add(sid)
        merged.append(s)
        covered_paths.add(s.get("projectPath", ""))

    # 3. Add day-tracker sessions only for uncovered projects
    dt_added = 0
    for s in dt_sessions:
        if s.get("projectPath", "") in covered_paths:
            continue  # Already have JSONL or index data for this project
        merged.append(s)
        dt_added += 1

    if dt_added:
        print(f"Merge: added {dt_added} day-tracker sessions for uncovered projects", file=sys.stderr)

    return merged


# ---------------------------------------------------------------------------
# Codex sessions
# ---------------------------------------------------------------------------

def find_codex_session_files(since: Optional[str] = None) -> list[Path]:
    """Find Codex session JSONL files, optionally filtered by date."""
    if not CODEX_SESSIONS_DIR.exists():
        return []

    if since:
        try:
            since_date = parse_timestamp(since).date()
        except ValueError:
            since_date = None
    else:
        since_date = None

    files = []
    for year_dir in sorted(CODEX_SESSIONS_DIR.iterdir()):
        if not year_dir.is_dir() or not year_dir.name.isdigit():
            continue
        for month_dir in sorted(year_dir.iterdir()):
            if not month_dir.is_dir() or not month_dir.name.isdigit():
                continue
            for day_dir in sorted(month_dir.iterdir()):
                if not day_dir.is_dir() or not day_dir.name.isdigit():
                    continue
                if since_date:
                    try:
                        dir_date = datetime(
                            int(year_dir.name), int(month_dir.name), int(day_dir.name)
                        ).date()
                        if dir_date < since_date:
                            continue
                    except ValueError:
                        continue
                for f in sorted(day_dir.glob("rollout-*.jsonl")):
                    files.append(f)
    return files


def load_codex_sessions(paths: list[Path]) -> list[dict]:
    """Load session metadata from Codex JSONL files."""
    sessions = []
    for path in paths:
        try:
            with open(path) as f:
                for line in f:
                    data = json.loads(line)
                    if data.get("type") == "session_meta":
                        payload = data["payload"]
                        # Extract first user prompt for context
                        first_prompt = ""
                        f.seek(0)
                        for inner_line in f:
                            item = json.loads(inner_line)
                            if item.get("type") == "response_item":
                                p = item.get("payload", {})
                                if p.get("role") == "user":
                                    for c in p.get("content", []):
                                        text = c.get("text", "")
                                        # Skip system instructions
                                        if text.startswith("# ") or text.startswith("<INSTRUCTIONS>"):
                                            continue
                                        if len(text) > 10:
                                            first_prompt = text[:200]
                                            break
                                if first_prompt:
                                    break

                        sessions.append({
                            "sessionId": payload.get("id", ""),
                            "projectPath": payload.get("cwd", ""),
                            "created": payload.get("timestamp", ""),
                            "modified": data.get("timestamp", ""),
                            "summary": "",
                            "firstPrompt": first_prompt,
                            "messageCount": 0,
                            "_source_file": str(path),
                            "_source": "codex",
                        })
                        break  # Only need session_meta
        except (json.JSONDecodeError, OSError) as e:
            print(f"Warning: Could not load Codex session {path}: {e}", file=sys.stderr)
    return sessions


# ---------------------------------------------------------------------------
# Digest period / last digest
# ---------------------------------------------------------------------------

def get_last_digest() -> Optional[dict]:
    """Get the most recent digest with its period.to timestamp."""
    if not DIGESTS_DIR.exists():
        return None

    digest_files = sorted(DIGESTS_DIR.glob("*.json"), reverse=True)
    for digest_file in digest_files:
        try:
            with open(digest_file) as f:
                data = json.load(f)
                if "period" in data and "to" in data["period"]:
                    data["_file"] = str(digest_file)
                    return data
        except (json.JSONDecodeError, OSError):
            continue
    return None


# ---------------------------------------------------------------------------
# Session filtering and grouping
# ---------------------------------------------------------------------------

def filter_sessions(sessions: list[dict], since: Optional[str]) -> list[dict]:
    """Filter sessions created or modified after the given timestamp."""
    if not since:
        return sessions

    since_dt = parse_timestamp(since)
    filtered = []
    for session in sessions:
        # For day-tracker sessions, use modified (last seen); for others, use created
        source = session.get("_source", "")
        if source == "day-tracker":
            ts_str = session.get("modified") or session.get("created")
        else:
            ts_str = session.get("created") or session.get("modified")

        if ts_str:
            try:
                ts_dt = parse_timestamp(ts_str)
                if ts_dt > since_dt:
                    filtered.append(session)
            except ValueError:
                filtered.append(session)  # Include on parse error (conservative)
        else:
            filtered.append(session)  # Include if no timestamp (conservative)
    return filtered


def get_project_name(project_path: str) -> str:
    """Extract a readable project name from the projectPath."""
    if not project_path:
        return "Unknown"

    path = Path(project_path)

    # Handle ~/.claude/skills/ paths
    if ".claude/skills" in project_path:
        parts = project_path.split(".claude/skills/")
        if len(parts) > 1:
            skill_name = parts[1].split("/")[0]
            return f"Skills ({skill_name})"
        return "Skills"

    # Handle ~/.agents/skills/ paths
    if ".agents/skills" in project_path:
        parts = project_path.split(".agents/skills/")
        if len(parts) > 1:
            skill_name = parts[1].split("/")[0]
            return f"Skills ({skill_name})"
        return "Skills"

    # Handle ~/.claude/ paths
    if ".claude" in project_path and "skills" not in project_path:
        return "Claude Code config"

    # Handle ~/.agents/ paths (not skills)
    if ".agents" in project_path and "skills" not in project_path:
        return ".agents"

    # Use the last meaningful path component
    name = path.name
    if not name or name in [".", ".."]:
        name = path.parent.name

    return name or "Unknown"


def categorise_project(project_path: str, project_name: str) -> str:
    """Determine the project type (client, personal, tools, planning, other)."""
    path_lower = project_path.lower() if project_path else ""

    # Skills and config are tools
    if ".claude" in path_lower or ".agents" in path_lower:
        return "tools"

    # Planning projects
    if "plans-and-reviews" in path_lower or "planning" in project_name.lower():
        return "planning"

    # Client projects often have a year-month prefix like "2025-09-".
    if "/Documents/Projects/" in project_path:
        folder = Path(project_path).name
        if re.match(r"^\d{4}-\d{2}-", folder):
            return "client"

    return "personal"


def group_by_project(sessions: list[dict]) -> dict:
    """Group sessions by project with raw summaries."""
    groups = {}

    for session in sessions:
        project_path = session.get("projectPath", "")
        project_name = get_project_name(project_path)

        if project_name not in groups:
            groups[project_name] = {
                "type": categorise_project(project_path, project_name),
                "project_path": project_path,
                "sessions": [],
            }

        groups[project_name]["sessions"].append({
            "sessionId": session.get("sessionId"),
            "summary": session.get("summary", ""),
            "firstPrompt": session.get("firstPrompt", "")[:200],
            "recentUserTurns": session.get("recentUserTurns", []),
            "recentAssistantTurns": session.get("recentAssistantTurns", []),
            "created": session.get("created"),
            "modified": session.get("modified"),
            "messageCount": session.get("messageCount", 0),
            "source": session.get("_source", "claude"),
        })

    return groups


# ---------------------------------------------------------------------------
# Digest generation and saving
# ---------------------------------------------------------------------------

def generate_draft_digest(groups: dict, period_from: Optional[str]) -> dict:
    """Generate a draft digest with placeholders for narrative content."""
    now = datetime.now(timezone.utc).astimezone()
    now_iso = now.isoformat()

    total_chats = sum(len(g["sessions"]) for g in groups.values())

    by_project = {}
    for project_name, group in groups.items():
        sessions = group["sessions"]
        session_summaries = [s["summary"] for s in sessions if s["summary"]]

        # For sessions without summaries, fall back to firstPrompt
        if not session_summaries:
            session_summaries = [s["firstPrompt"] for s in sessions if s.get("firstPrompt")]

        claude_count = sum(1 for s in sessions if s.get("source") in ("claude", "claude-jsonl"))
        codex_count = sum(1 for s in sessions if s.get("source") == "codex")
        dt_count = sum(1 for s in sessions if s.get("source") == "day-tracker")

        # Collect recent turns across all sessions for this project
        all_user_turns = []
        all_assistant_turns = []
        for s in sessions:
            all_user_turns.extend(s.get("recentUserTurns") or [])
            all_assistant_turns.extend(s.get("recentAssistantTurns") or [])

        by_project[project_name] = {
            "type": group["type"],
            "chat_count": len(sessions),
            "claude_count": claude_count,
            "codex_count": codex_count,
            "day_tracker_count": dt_count,
            "combined_summary": (
                f"[{len(sessions)} sessions - summarise based on: {'; '.join(session_summaries[:5])}]"
                if session_summaries
                else f"[{len(sessions)} sessions - no summaries available]"
            ),
            "all_tasks_completed": [],
            "all_tasks_in_progress": [],
            "all_blockers": [],
            "_session_summaries": session_summaries,
            "_recent_user_turns": all_user_turns,
            "_recent_assistant_turns": all_assistant_turns,
        }

    return {
        "generated": now_iso,
        "period": {
            "from": period_from or "unknown",
            "to": now_iso,
        },
        "chat_count": total_chats,
        "by_project": by_project,
        "key_completions": ["[To be filled by Claude based on session summaries]"],
        "still_in_progress": ["[To be filled by Claude based on session summaries]"],
        "all_blockers": ["[To be filled by Claude based on session summaries]"],
    }


def save_digest(digest: dict, date: str) -> Path:
    """Save the digest to a file. Returns the file path."""
    DIGESTS_DIR.mkdir(parents=True, exist_ok=True)
    output_path = DIGESTS_DIR / f"{date}.json"

    with open(output_path, "w") as f:
        json.dump(digest, f, indent=2)

    return output_path


# ---------------------------------------------------------------------------
# Public helpers (status, main)
# ---------------------------------------------------------------------------

def _collect_all_sessions(period_from: Optional[str]) -> tuple[list[dict], list[dict]]:
    """
    Collect all sessions from all sources, merged and filtered.

    Returns (claude_sessions, codex_sessions) — already filtered by period_from.
    """
    # Source 1: JSONL scan (primary)
    jsonl_sessions = scan_jsonl_sessions(period_from)

    # Source 3: sessions-index.json (legacy, non-stale only)
    index_files = find_session_files()
    index_sessions = load_sessions(index_files, since=period_from)

    # Source 2: day-tracker (supplementary)
    dt_sessions = load_sessions_from_day_tracker(period_from)

    # Merge
    claude_sessions = merge_sessions(index_sessions, jsonl_sessions, dt_sessions, period_from)

    # Codex sessions (unchanged)
    codex_files = find_codex_session_files(period_from)
    codex_sessions = load_codex_sessions(codex_files)

    return claude_sessions, codex_sessions


def get_status() -> dict:
    """Get current status without generating a digest."""
    last_digest = get_last_digest()
    period_from = last_digest["period"]["to"] if last_digest else None

    claude_sessions, codex_sessions = _collect_all_sessions(period_from)
    all_combined = claude_sessions + codex_sessions
    new_sessions = filter_sessions(all_combined, period_from)

    today = datetime.now().strftime("%Y-%m-%d")
    today_digest_exists = (DIGESTS_DIR / f"{today}.json").exists()

    # Breakdown by source
    source_counts: dict[str, int] = {}
    for s in new_sessions:
        src = s.get("_source", "unknown")
        source_counts[src] = source_counts.get(src, 0) + 1

    return {
        "last_digest_date": last_digest["_file"].split("/")[-1].replace(".json", "") if last_digest else None,
        "last_digest_period_to": period_from,
        "total_sessions_found": len(all_combined),
        "sessions_since_last_digest": len(new_sessions),
        "sessions_by_source": source_counts,
        "projects_with_new_sessions": len(group_by_project(new_sessions)),
        "today_digest_exists": today_digest_exists,
    }


def main():
    parser = argparse.ArgumentParser(
        description="Generate Claude Code + Codex chat digests with guaranteed file saving."
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output JSON to stdout (for Claude to read and enhance)",
    )
    parser.add_argument(
        "--status",
        action="store_true",
        help="Check status without generating",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Force regenerate even if today's digest exists",
    )

    args = parser.parse_args()

    # Status mode
    if args.status:
        status = get_status()
        if args.json:
            print(json.dumps(status, indent=2))
        else:
            print(f"Last digest:      {status['last_digest_date'] or 'None'}")
            print(f"Period ends:      {status['last_digest_period_to'] or 'N/A'}")
            print(f"Sessions found:   {status['total_sessions_found']}")
            print(f"  by source:      {status['sessions_by_source']}")
            print(f"Since cutoff:     {status['sessions_since_last_digest']}")
            print(f"Projects active:  {status['projects_with_new_sessions']}")
            print(f"Today's digest:   {'exists' if status['today_digest_exists'] else 'missing'}")
        return

    # Check if today's digest already exists
    today = datetime.now().strftime("%Y-%m-%d")
    today_path = DIGESTS_DIR / f"{today}.json"

    if today_path.exists() and not args.force:
        print(f"Today's digest already exists: {today_path}")
        print("Use --force to regenerate.")
        return

    # Generate the digest
    last_digest = get_last_digest()
    period_from = last_digest["period"]["to"] if last_digest else None

    claude_sessions, codex_sessions = _collect_all_sessions(period_from)
    print(f"Loaded {len(claude_sessions)} Claude sessions (all sources)", file=sys.stderr)
    print(f"Loaded {len(codex_sessions)} Codex sessions", file=sys.stderr)

    all_combined = claude_sessions + codex_sessions
    new_sessions = filter_sessions(all_combined, period_from)
    print(f"Filtered to {len(new_sessions)} sessions since {period_from or 'beginning'}", file=sys.stderr)

    groups = group_by_project(new_sessions)
    print(f"Grouped into {len(groups)} projects", file=sys.stderr)

    digest = generate_draft_digest(groups, period_from)

    if args.json:
        print(json.dumps(digest, indent=2))
    else:
        output_path = save_digest(digest, today)
        print(f"Saved digest to: {output_path}")
        print(f"Chat count: {digest['chat_count']}")
        print(f"Projects: {', '.join(groups.keys())}")
        print("\nNote: combined_summary fields contain placeholders. Claude can enhance these.")


if __name__ == "__main__":
    main()
